# Acesse https://aka.ms/customizecontainer para saber como personalizar seu contêiner de depuração e como o Visual Studio usa este Dockerfile para criar suas imagens para uma depuração mais rápida.

# Esta fase é usada durante a execução no VS no modo rápido (Padrão para a configuração de Depuração)
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
USER $APP_UID
WORKDIR /app
EXPOSE 8080
EXPOSE 8081


# Esta fase é usada para compilar o projeto de serviço
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["MotoHub.API/MotoHub.API.sln", "MotoHub.API/"]
COPY ["MotoHub.API/MotoHub.API.csproj", "MotoHub.API/"]
COPY ["MotoHub.Domain/MotoHub.Domain.csproj", "MotoHub.Domain/"]
COPY ["MotoHub.CrossCutting/MotoHub.CrossCutting.csproj", "MotoHub.CrossCutting/"]
COPY ["MotoHub.Application/MotoHub.Application.csproj", "MotoHub.Application/"]
COPY ["MotoHub.Infrastructure/MotoHub.Infrastructure.csproj", "MotoHub.Infrastructure/"]
RUN dotnet restore "MotoHub.API/MotoHub.API.csproj"
COPY . .
WORKDIR "/src/."
RUN dotnet build "MotoHub.API/MotoHub.API.csproj" -c $BUILD_CONFIGURATION -o /app/build

# Esta fase é usada para publicar o projeto de serviço a ser copiado para a fase final
FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "MotoHub.API/MotoHub.API.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

# Esta fase é usada na produção ou quando executada no VS no modo normal (padrão quando não está usando a configuração de Depuração)
FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "MotoHub.API.dll"]